version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: expense-app
    build: .
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ./gradlew bootRun

  mongo:
    image: mongo:latest
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
